name: Build Extension

on: push

jobs:
  package-extension:
    name: Build Extension
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install VSCE
        run: npm install --global @vscode/vsce
      - name: Package extension
        run: vsce package --no-rewrite-relative-links
      - name: Upload package artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          path: energyplus-modelkit-*.vsix
